language: python
matrix:
  include:
  - python: 3.5-dev
    env: TOXENV=py35,coveralls
  - python: 3.4
    env: TOXENV=py34
  - python: 3.3
    env: TOXENV=py33
  - python: 2.7
    env: TOXENV=py27,coveralls
  - python: pypy
    env: TOXENV=pypy
install: pip install tox
script: tox
deploy:
  provider: pypi
  user: nickfrostatx
  password:
    secure: gBrVjYdZeCZieLOPOvIIt0rj2oxUTANZcvK8idC+INmLVICemoKbkP1I6u723T6ItEb0gTNTvo8EqNh4v+58crlViTRB95QiUKqx1rGv1XDe4if4dGiU8mPk/xPEaKKqgzobS7yfZberIsSJFdPUoEZgAfUI9zSarphkE3kAv9Romgc2wBKDdynSCgpn6dPav0lkqNH2+NBFLVkBUcjOoMWXvhDpcbpsGg1tIlN1okP41tOcD37JRcq2LYyAWMNpQq52B2bSTykZZEqD+Sygea+0/JbpjwdxuzcuPm+A43T1W+xA0+0/AJ89LPg/tJD3YtHs5Fz53u/Kb9F4LMjNm1La1kBhXq97BuFJD/+lWPTY5Mx3egwiIJIeuMO0zERvqSmpwxr0yb1hIYMgcOzCDzDLWOocjimndhAFdAEMHKI+8SKMxi92GgVJkwao+ulQgf74dkmPb3Nto2eUuf0fD8qNEEEfCzmWyIVEpvv1MtSncUGdeGvigH1YGrReB55zs3DvLsDtLZ+mW4uRpN8MtThraHWaSN9hZZRBj+aZIGUBDYN+E+yES7PPiPLoKueLK89K9MAreUZSq6kYWd9Y4f/z6sff6YrhMsTcZQOd/LAUkiyvY+a3LqFkL8pOw7qjs+dV2/68XtPvDghDoFpDdKJEUXMKF3tauqKD8dokkg8=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_JOB_NUMBER = *.1
